NCO:
  GitHubRepo:
    Owner: djfdyuruiry
    Name: cnc-new-construction-options
  Release: latest
  AssetPrefix: vanilla-conquer-nco-${OS}

# TODO: Read ICO files and add to UI as we install
# TODO: Add dos demo files https://cnc.fandom.com/wiki/Command_%26_Conquer_demo and add nco feature matching info here https://github.com/TheAssemblyArmada/Vanilla-Conquer/wiki/Installing-VanillaTD#patching-cc95-gold-with-demo-for-dos-mode
TiberianDawn:
  Name: Tiberian Dawn
  DisplayName: >-
    Command & Conquer: Tiberian Dawn
  NcoZipPath: td
  InstallPostfix: td
  DiscImages:
    - Name: GDI
      Required: true
      Sources:
        - Name: cnc-comm
          Url: https://bigdownloads.cnc-comm.com/cnc1/CNC95_GDI.zip
          File: CNC95_GDI.iso
      SplashScreenFile: SETUP.BMP
      Provides:
        _root:
          - CCLOCAL.MIX
          - CONQUER.MIX
          - DESEICNH.MIX
          - DESERT.MIX
          - SOUNDS.MIX
          - SPEECH.MIX
          - TEMPERAT.MIX
          - TEMPICNH.MIX
          - TRANSIT.MIX
          - UPDATE.MIX
          - UPDATEC.MIX
          - WINTER.MIX
          - WINTICNH.MIX
        GDI:
          - GENERAL.MIX
          - MOVIES.MIX
          - SCORES.MIX
    - Name: NOD
      Sources:
        - Name: cnc-comm
          Url: https://bigdownloads.cnc-comm.com/cnc1/CNC95_Nod.zip
          File: CNC95_Nod.iso
      SplashScreenFile: SETUP.BMP
      Provides:
        NOD:
          - GENERAL.MIX
          - MOVIES.MIX
          - SCORES.MIX
    - Name: CovertOps
      DisplayName: >-
        Covert Operations (Expansion)
      Sources:
        - Name: cnc-comm
          Url: https://bigdownloads.cnc-comm.com/cnc1/CNC_Covertops.zip
          File: CD3_Covertops.bin
      Provides:
        _root:
          - INSTALL\\SC-000.MIX
          - INSTALL\\SC-001.MIX
          - INSTALL\\SPEECH.MIX
        COVERTOPS:
          - GENERAL.MIX
          - MOVIES.MIX
          - SCORES.MIX
  ZipUrls: []

RedAlert:
  Name: Red Alert
  DisplayName: >-
    Command & Conquer: Red Alert
  NcoZipPath: ra
  InstallPostfix: ra
  DiscImages:
    - Name: ALLIES
      DisplayName: Allies
      Required: true
      Sources:
        - Name: cnc-comm
          Url: https://bigdownloads.cnc-comm.com/ra/RA_Allies.zip
          File: CD1_ALLIES.iso
      SplashScreenFile: SETUP95\\SETUP.BMP
      Provides:
        _root:
          - INSTALL\\REDALERT.MIX
        ALLIES:
          - MAIN.MIX
    - Name: SOVIET
      DisplayName: Soviet
      Sources:
        - Name: cnc-comm
          Url: https://bigdownloads.cnc-comm.com/ra/RA_Soviet.zip
          File: CD2_Soviet.iso
      SplashScreenFile: SETUP95\\SETUP.BMP
      Provides:
        _root:
          - INSTALL\\REDALERT.MIX
        SOVIET:
          - MAIN.MIX
    - Name: COUNTERSTRIKE
      DisplayName: Counterstrike
      Sources:
        - Name: cnc-comm
          Url: https://bigdownloads.cnc-comm.com/ra/RA_Counterstrike.zip
          File: CD3_Counterstrike.bin
      SplashScreenFile: SETUP95\\SETUP.BMP
      Provides:
        COUNTERSTRIKE:
          - MAIN.MIX
    - Name: AFTERMATH
      DisplayName: The Aftermath
      Sources:
        - Name: cnc-comm
          Url: https://bigdownloads.cnc-comm.com/ra/RA_Aftermath.zip
          File: CD4_Aftermath.bin
      SplashScreenFile: SETUP95\\SETUP.BMP
      Provides:
        AFTERMATH:
          - MAIN.MIX
  # TODO: SplashScreenUrl, pull image from internet for display during install
  ZipUrls:
    - Name: TheLostFiles
      DisplayName:
        The Lost Files ('Counterstrike'/'The Aftermath' Cutscenes)
      Url: https://www.mediafire.com/download/4b767436vd2et54/ra_TLF_Videos_v3-en.zip
      ProvidesFilesEndingWith: .MIX
