NCO:
  GitHubRepo:
    Owner: djfdyuruiry
    Name: cnc-new-construction-options
  Release: latest
  AssetPrefix: vanilla-conquer-nco-${OS}

# TODO: Add dos demo files https://cnc.fandom.com/wiki/Command_%26_Conquer_demo and add nco feature matching info here https://github.com/TheAssemblyArmada/Vanilla-Conquer/wiki/Installing-VanillaTD#patching-cc95-gold-with-demo-for-dos-mode
TiberianDawn:
  NcoZipPath: td
  InstallPostfix: td
  DiscImages:
    GDI:
      Sources:
        cnc-comm:
          Url: https://bigdownloads.cnc-comm.com/cnc1/CNC95_GDI.zip
          File: CNC95_GDI.iso
      Provides:
        _root:
          - CCLOCAL.MIX
          - CONQUER.MIX
          - DESEICNH.MIX
          - DESERT.MIX
          - SOUNDS.MIX
          - SPEECH.MIX
          - TEMPERAT.MIX
          - TEMPICNH.MIX
          - TRANSIT.MIX
          - UPDATE.MIX
          - UPDATEC.MIX
          - WINTER.MIX
          - WINTICNH.MIX
        GDI:
          - GENERAL.MIX
          - MOVIES.MIX
          - SCORES.MIX
    NOD:
      Sources:
        cnc-comm:
          Url: https://bigdownloads.cnc-comm.com/cnc1/CNC95_Nod.zip
          File: CNC95_Nod.iso
      Provides:
        NOD:
          - GENERAL.MIX
          - MOVIES.MIX
          - SCORES.MIX
    CovertOps:
      Sources:
        cnc-comm:
          Url: https://bigdownloads.cnc-comm.com/cnc1/CNC_Covertops.zip
          File: CD3_Covertops.bin
      Provides:
        _root:
          - INSTALL\\SC-000.MIX
          - INSTALL\\SC-001.MIX
          - INSTALL\\SPEECH.MIX
        COVERTOPS:
          - GENERAL.MIX
          - MOVIES.MIX
          - SCORES.MIX
  ZipUrls: {}

RedAlert:
  NcoZipPath: ra
  InstallPostfix: ra
  DiscImages:
    ALLIES:
      Sources:
        cnc-comm:
          Url: https://bigdownloads.cnc-comm.com/ra/RA_Allies.zip
          File: CD1_ALLIES.iso
      Provides:
        _root:
          - INSTALL\\REDALERT.MIX
        ALLIES:
          - MAIN.MIX
    SOVIET:
      Sources:
        cnc-comm:
          Url: https://bigdownloads.cnc-comm.com/ra/RA_Soviet.zip
          File: CD2_Soviet.iso
      Provides:
        _root:
          - INSTALL\\REDALERT.MIX
        SOVIET:
          - MAIN.MIX
    COUNTERSTRIKE:
      Sources:
        cnc-comm:
          Url: https://bigdownloads.cnc-comm.com/ra/RA_Counterstrike.zip
          File: CD3_Counterstrike.bin
      Provides:
        COUNTERSTRIKE:
          - MAIN.MIX
    AFTERMATH:
      Sources:
        cnc-comm:
          Url: https://bigdownloads.cnc-comm.com/ra/RA_Aftermath.zip
          File: CD4_Aftermath.bin
      Provides:
        AFTERMATH:
          - MAIN.MIX
  ZipUrls:
    TheLostFiles:
      Url: https://www.mediafire.com/download/4b767436vd2et54/ra_TLF_Videos_v3-en.zip
      ProvidesFilesEndingWith: .MIX
