name: Feature Request
description: Suggest an enhancement/change to the game engine

title: "[Feature] "
labels: ["feature", "triage"]

assignees:
  - djfdyuruiry

body:
  - type: markdown
    attributes:
      value: |
        Use the form below to suggest a new feature or enhancement.

        Please be specific about the Game you would like to see changed.
  - type: checkboxes
    id: game
    attributes:
      label: Which game would this feature be added to?
      description: You can select multiple
      options:
        - label: Tiberian Dawn
        - label: Red Alert
    validations:
      required: true
  - type: textarea
    id: feature-suggestion
    attributes:
      label: Describe the feature or enhancement you would like to see.
      description: Be as detailed as possible.
      placeholder: Enter details here
    validations:
      required: true
