blank_issues_enabled: false
contact_links:
  - name: New Construction Options Enhancements
    url: https://github.com/djfdyuruiry/cnc-new-construction-options/wiki/2.Enhancements
    about: See if the feature you want is already listed here
  - name: New Construction Options Bug Fixes
    url: https://github.com/djfdyuruiry/cnc-new-construction-options/wiki/2d.Bug-Fixes.md
    about: See if the bug you have has been fixed in the latest version here
