#pragma once
/**
 * This file was generated by CMake file `../cmake/NcoRules.cmake` using
 * rule JSON files:
 *   - rules/00.Enhancements.json
 *   - rules/01.Game.Map.json
 *   - rules/02.Game.Harvesting.json
 *   - rules/03.Game.Factories.json
 *   - rules/04.Game.Repair.json
 *   - rules/05.Game.Misc.json
 *   - rules/06.Game.House.json
 *   - rules/07.Game.Scenarios.json
 *   - rules/08.Game.Cheats.json
 */

// generated code START

// [Enhancements]
#define ENHANCEMENTS_SECTION "Enhancements"

#define ASTAR_PATH_FINDING_RULE "AStarPathFinding"
#define RALLY_POINTS_RULE "RallyPoints"

// [Game.Map]
#define GAME_MAP_SECTION "Game.Map"

#define MAX_BUILD_DISTANCE_RULE "MaxBuildDistance"
#define PREVENT_BUILDING_IN_SHROUD_RULE "PreventBuildingInShroud"
#define ALLOW_BUILDING_BESIDE_WALLS_RULE "AllowBuildingBesideWalls"
#define TIBERIUM_GROWS_RULE "TiberiumGrows"
#define TIBERIUM_SPREADS_RULE "TiberiumSpreads"
#define SLOW_TIBERIUM_GROWTH_AND_SPREAD_RULE "SlowTiberiumGrowthAndSpread"
#define TIBERIUM_GROWTH_RATE_RULE "TiberiumGrowthRate"
#define TIBERIUM_SPREAD_RATE_RULE "TiberiumSpreadRate"
#define TIBERIUM_INFANTRY_DAMAGE_RULE "TiberiumInfantryDamage"
#define TIBERIUM_BLOSSOM_TREE_DAMAGE_RULE "TiberiumBlossomTreeDamage"

// [Game.Harvesting]
#define GAME_HARVESTING_SECTION "Game.Harvesting"

#define HARVESTER_PIPS_RULE "HarvesterPips"
#define CREDITS_PER_TIBERIUM_SCOOP_RULE "CreditsPerTiberiumScoop"
#define MAX_HARVESTER_CAPACITY_RULE "MaxHarvesterCapacity"

// [Game.Factories]
#define GAME_FACTORIES_SECTION "Game.Factories"

#define PRODUCTION_STEPS_PER_TICK_RULE "ProductionStepsPerTick"
#define FACTORY_COUNT_STEP_MULTIPLIER_RULE "FactoryCountStepMultiplier"
#define TOTAL_PRODUCTION_STEPS_RULE "TotalProductionSteps"

// [Game.Repair]
#define GAME_REPAIR_SECTION "Game.Repair"

#define BUILDING_REPAIR_FACTOR_RULE "BuildingRepairFactor"
#define BUILDING_REPAIR_STRENGTH_STEP_RULE "BuildingRepairStrengthStep"
#define UNIT_REPAIR_FACTOR_RULE "UnitRepairFactor"
#define UNIT_REPAIR_STRENGTH_STEP_RULE "UnitRepairStrengthStep"
#define AIRCRAFT_REPAIR_FACTOR_RULE "AircraftRepairFactor"
#define AIRCRAFT_REPAIR_STRENGTH_STEP_RULE "AircraftRepairStrengthStep"

// [Game.Misc]
#define GAME_MISC_SECTION "Game.Misc"

#define SMART_DEFENSE_RULE "SmartDefense"
#define TARGET_TREES_RULE "TargetTrees"
#define MCV_REDEPLOYABLE_RULE "McvRedeployable"
#define SPAWN_VISCEROIDS_RULE "SpawnVisceroids"
#define VEHICLES_DO_THREE_POINT_TURNS_RULE "VehiclesDoThreePointTurns"
#define SHOW_BIBS_ON_BUILDINGS_RULE "ShowBibsOnBuildings"
#define SHOW_CIVILIAN_NAMES_RULE "ShowCivilianNames"
#define ONLY_ALLOW_NUKE_IF_ALL_PARTS_HAVE_BEEN_COLLECTED_RULE "OnlyAllowNukeIfAllPartsHaveBeenCollected"
#define ONLY_ALLOW_USING_ONE_NUKE_PER_SCENARIO_RULE "OnlyAllowUsingOneNukePerScenario"
#define HELIPADS_AND_AIRCRAFT_BOUGHT_SEPARATELY_RULE "HelipadsAndAircraftBoughtSeparately"
#define DESTROYED_BUILDINGS_HAVE_SURVIVORS_RULE "DestroyedBuildingsHaveSurvivors"

// [Game.House]
#define GAME_HOUSE_SECTION "Game.House"

#define HIDE_TEMPLE_FROM_GDI_RULE "HideTempleFromGdi"
#define HIDE_OBELISK_FROM_GDI_RULE "HideObeliskFromGdi"
#define HIDE_APC_FROM_NOD_RULE "HideApcFromNod"
#define HIDE_ROCKET_LAUNCHER_FROM_NOD_RULE "HideRocketLauncherFromNod"
#define HIDE_HELIPAD_FROM_NOD_RULE "HideHelipadFromNod"
#define HIDE_ADVANCED_COMM_CENTER_FROM_NOD_RULE "HideAdvancedCommCenterFromNod"
#define ONLY_GDI_CAN_USE_ION_CANNON_RULE "OnlyGdiCanUseIonCannon"
#define ONLY_NOD_CAN_USE_NUKE_RULE "OnlyNodCanUseNuke"

// [Game.Scenarios]
#define GAME_SCENARIOS_SECTION "Game.Scenarios"

#define SET_BUILD_LEVEL_TO_1_IN_GDI_SCENARIO_2_RULE "SetBuildLevelTo1InGdiScenario2"
#define RENAME_TECH_CENTER_TO_PRISON_IN_NOD_SCENARIO_3_RULE "RenameTechCenterToPrisonInNodScenario3"
#define HIDE_BAZOOKA_FROM_GDI_UNTIL_SCENARIO_8_RULE "HideBazookaFromGdiUntilScenario8"
#define HIDE_ROCKET_LAUNCHER_FROM_GDI_UNTIL_SCENARIO_9_RULE "HideRocketLauncherFromGdiUntilScenario9"
#define HIDE_SANDBAG_FROM_GDI_UNTIL_SCENARIO_9_RULE "HideSandbagFromGdiUntilScenario9"
#define ALLOW_NOD_TO_BUILD_ADVANCED_POWER_IN_SCENARIO_12_RULE "AllowNodToBuildAdvancedPowerInScenario12"
#define REQUIRE_TECH_CENTRE_FOR_STEALTH_TANK_IN_NOD_SCENARIO_11_RULE "RequireTechCentreForStealthTankInNodScenario11"

// [Game.Cheats]
#define GAME_CHEATS_SECTION "Game.Cheats"

#define ALLOW_BUILDING_ALL_FOR_CURRENT_HOUSE_RULE "AllowBuildingAllForCurrentHouse"
#define UNITS_ARE_INDESTRUCTIBLE_RULE "UnitsAreIndestructible"
#define INFANTRY_AUTO_SCATTERS_RULE "InfantryAutoScatters"
#define GIVE_ATTACKERS_AN_ADVANTAGE_RULE "GiveAttackersAnAdvantage"
#define SPEEDY_SUPERWEAPONS_RULE "SpeedySuperweapons"

// generated code END
