name: linux

on:
  workflow_dispatch:
    inputs:
      c_compiler:
        description: 'C Compiler (e.g. gcc, clang)'
        required: false
        default: 'gcc'
      cpp_compiler:
        description: 'C++ Compiler (e.g. g++)'
        required: false
        default: 'g++'
      preset:
        description: 'Build preset (e.g., nco-tiberian-dawn)'
        required: false
        default: 'nco-tiberian-dawn'
      os:
        description: 'OS to run on (e.g., ubuntu-24.04)'
        required: false
        default: 'ubuntu-24.04'
  pull_request:
  push:
    branches:
      - main

jobs:
  create_dev_release:
    runs-on: ubuntu-22.04
    steps:
    - name: Create Development release
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
      uses: "0xDylan/action-auto-releases-n20@v1.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"

  vanilla-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        compiler:
          - cc: "${{ github.event.inputs.c_compiler || 'gcc' }}"
            cxx: "${{ github.event.inputs.cpp_compiler || 'g++' }}"
        preset:
          - "${{ github.event.inputs.preset || 'nco-tiberian-dawn' }}"
        os:
          - "${{ github.event.inputs.os || 'ubuntu-24.04' }}"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 0
        ref: "${{ github.event.pull_request.head.sha || github.sha }}"

    - name: Set Git Info
      id: gitinfo
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Install dependencies
      run: |
        sudo apt-get update -qq > /dev/null
        sudo apt-get install -qq -y clang-format-14 libsdl2-dev libopenal-dev ninja-build > /dev/null

    - name: Build Vanilla Conquer
      env:
        CC: ${{ matrix.compiler.cc }}
        CXX: ${{ matrix.compiler.cxx }}
        VC_CXX_FLAGS: "-w;-Wwrite-strings;-Werror=write-strings"
      run: |
        cmake --workflow --preset ${{ matrix.preset }}

    - name: Check formatting
      if: ${{ matrix.compiler.cc == 'clang' && matrix.preset == 'testing'}}
      run: |
        cmake --build build/testing --target format
        git diff --exit-code

    - name: Create archives
      if: ${{ matrix.preset != 'testing' &&  matrix.preset != 'nonet' }}
      run: |
        cp ./build/${{ matrix.preset }}/RelWithDebInfo/vanillatd ./build/${{ matrix.preset }}/RelWithDebInfo/vanillatd.dbg
        # cp ./build/${{ matrix.preset }}/RelWithDebInfo/vanillara ./build/${{ matrix.preset }}/RelWithDebInfo/vanillara.dbg
        strip --strip-all ./build/${{ matrix.preset }}/RelWithDebInfo/vanillatd
        # strip --strip-all ./build/${{ matrix.preset }}/RelWithDebInfo/vanillara
        objcopy --add-gnu-debuglink=./build/${{ matrix.preset }}/RelWithDebInfo/vanillatd.dbg ./build/${{ matrix.preset }}/RelWithDebInfo/vanillatd
        # objcopy --add-gnu-debuglink=./build/${{ matrix.preset }}/RelWithDebInfo/vanillara.dbg ./build/${{ matrix.preset }}/RelWithDebInfo/vanillara
        mkdir artifact
        7z a artifact/vanilla-conquer-${{ matrix.preset }}-linux-${{ matrix.compiler.cc }}-${{ matrix.os }}-x86_64-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/${{ matrix.preset }}/RelWithDebInfo/vanillatd
        # ./build/${{ matrix.preset }}/RelWithDebInfo/vanillara
        7z a artifact/vanilla-conquer-${{ matrix.preset }}-linux-${{ matrix.compiler.cc }}-${{ matrix.os }}-x86_64-${{ steps.gitinfo.outputs.sha_short }}-debug.zip ./build/${{ matrix.preset }}/RelWithDebInfo/vanillatd.dbg
        # ./build/${{ matrix.preset }}/RelWithDebInfo/vanillara.dbg

    - name: Add internal tools to archive
      if: ${{ matrix.preset == 'internal' || matrix.preset == 'nco-tiberian-dawn' }}
      run: |
        cp ./build/${{ matrix.preset }}/RelWithDebInfo/vanillamix ./build/${{ matrix.preset }}/RelWithDebInfo/vanillamix.dbg
        objcopy --add-gnu-debuglink=./build/${{ matrix.preset }}/RelWithDebInfo/vanillamix.dbg ./build/${{ matrix.preset }}/RelWithDebInfo/vanillamix
        strip --strip-all ./build/${{ matrix.preset }}/RelWithDebInfo/vanillamix
        7z a artifact/vanilla-conquer-${{ matrix.preset }}-linux-${{ matrix.compiler.cc }}-${{ matrix.os }}-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/${{ matrix.preset }}/RelWithDebInfo/vanillamix
        7z a artifact/vanilla-conquer-${{ matrix.preset }}-linux-${{ matrix.compiler.cc }}-${{ matrix.os }}-${{ steps.gitinfo.outputs.sha_short }}-debug.zip ./build/${{ matrix.preset }}/RelWithDebInfo/vanillamix.dbg

    - name: Upload artifact
      if: ${{ matrix.preset != 'testing' &&  matrix.preset != 'nonet' }}
      uses: actions/upload-artifact@v4
      with:
        name: vanilla-conquer-${{ matrix.preset }}-linux-${{ matrix.compiler.cc }}-${{ matrix.os }}-x86_64
        path: artifact

    - name: Upload development release
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && matrix.preset != 'testing' &&  matrix.preset != 'nonet' }}
      uses: softprops/action-gh-release@v2
      with:
        name: Development Build
        tag_name: "latest"
        prerelease: true
        files: |
          artifact/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload tagged release
      if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.preset != 'testing' &&  matrix.preset != 'nonet' }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifact/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
