name: macos

on:
  workflow_dispatch:
    inputs:
      preset:
        description: 'Build preset (e.g., nco-tiberian-dawn)'
        required: false
        default: 'nco-tiberian-dawn'

  # TODO: Builds *only* run for PRs and *only* if you label the PR with 'macos'.
  #       I want to save on action minute usage for now.
  pull_request:
    paths:
      - .clang-format
      - CMake**
      - .github/workflows/macos.yml
      - cmake/**
      - common/**
      - redalert/**
      - resources
      - tests/**
      - tiberiandawn/**
      - tools/**

  # push:
  #   branches:
  #     - main
  #   paths:
  #     - .clang-format
  #     - CMake**
  #     - .github/workflows/macos.yml
  #     - cmake/**
  #     - common/**
  #     - redalert/**
  #     - resources
  #     - tests/**
  #     - tiberiandawn/**
  #     - tools/**

concurrency:
  group: ${{ github.ref }}__macos
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  vanilla-macos:
    if: contains(github.event.pull_request.labels.*.name, 'macos')
    runs-on: macos-15
    strategy:
      matrix:
        preset:
          - "${{ github.event.inputs.preset || 'nco-tiberian-dawn' }}"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 0
        ref: "${{ github.event.pull_request.head.sha || github.sha }}"

    - name: Set Git Info
      id: gitinfo
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Install homebrew deps
      run: |
        brew install dylibbundler imagemagick jinja2-cli jq mono ninja python3

    - name: Scan for Preset Files in Changes
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          ci:
            - .github/workflows/linux.yml
          nco:
            - .clang-format
            - CMake**
            - cmake/**
            - common/**
            - resources
            - tools/**
          ra:
            - redalert/**
          td:
            - tiberiandawn/**
          lua:
            - common/lua/scripts/**
            - tiberiandawn/lua/scripts/**
            - tests/lua/scripts/**

    - name: Init Lua
      if: steps.changes.outputs.lua == 'true'
      uses: leafo/gh-actions-lua@v11
      with:
        luaVersion: "5.4"

    - name: Run Lua Tests
      if: steps.changes.outputs.lua == 'true'
      run: |
        ./scripts/98.run-lua-unit-tests.sh \
        && ./scripts/99.test-lua-script.sh ./tiberiandawn/lua/scripts/scg01ea.lua

    - name: Set Preset
      id: set_preset
      run: |
        PRESET=""

        if [ "${{ steps.changes.outputs.nco }}" = "true" ]; then
          echo "Changes to shared files detected - building everything using cmake preset: nco"
          PRESET="nco"
        elif [ "${{ steps.changes.outputs.ra }}" = "true" ] && [ "${{ steps.changes.outputs.td }}" = "true" ]; then
          echo "Red Alert & Tiberian Dawn changes detected - building both using cmake preset: nco"
          PRESET="nco"
        elif [ "${{ steps.changes.outputs.ra }}" = "true" ] ; then
          echo "Only Red Alert changes detected - using cmake preset: nco-red-alert"
          PRESET="nco-red-alert"
        elif [ "${{ steps.changes.outputs.td }}" = "true" ]; then
          echo "Only Tiberian Dawn changes detected - using cmake preset: nco-tiberian-dawn"
          PRESET="nco-tiberian-dawn"
        elif [ "${{ steps.changes.outputs.ci }}" = "true" ]; then
          echo "Workflow yml changes detected - testing workflow changes using cmake preset: nco"
          PRESET="nco"
        else
          echo "WARNING: Unable to match changed files to a preset - defaulting to building everything using cmake preset: nco"
          PRESET="nco"
        fi

        echo "preset=${PRESET}" >> $GITHUB_OUTPUT

    - name: Init vcpkg
      run: |
        ./scripts/bin/vcpkg --init
        ./scripts/bin/vcpkg fetch nuget

    - name: Init vcpkg Binary Cache
      run: |
        cd "$(dirname "$(./scripts/bin/vcpkg fetch nuget)")"

        mono nuget.exe sources add \
          -Source "https://nuget.pkg.github.com/djfdyuruiry/index.json" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "djfdyuruiry" \
          -Password "${{ secrets.GITHUB_TOKEN }}"

        mono nuget.exe setapikey "${{ secrets.GITHUB_TOKEN }}" \
          -Source "https://nuget.pkg.github.com/djfdyuruiry/index.json"

    - name: Create Universal vcpkg Triplet
      env:
        VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/djfdyuruiry/index.json,readwrite"
      run: |
        installed_path=build/${{ steps.set_preset.outputs.preset }}/vcpkg_installed

        mkdir -p $installed_path

        mkdir /tmp/vcpkg-arm64
        mkdir /tmp/vcpkg-x64

        ./scripts/bin/vcpkg install --triplet=arm64-osx --x-install-root=/tmp/vcpkg-arm64
        ./scripts/bin/vcpkg install --triplet=x64-osx --x-install-root=/tmp/vcpkg-x64

        python -m venv /tmp/vcpkg.venv
        . /tmp/vcpkg.venv/bin/activate

        python -m ensurepip
        python -m pip install lipomerge

        python -m lipomerge /tmp/vcpkg-arm64/arm64-osx /tmp/vcpkg-x64/x64-osx $installed_path/uni-osx

    - name: Build Vanilla Conquer
      env:
        CMAKE_MAKE_PROGRAM: ninja
        CMAKE_OSX_ARCHITECTURES: "arm64;x86_64"
        VC_CXX_FLAGS: "-w;-Wwrite-strings;-Werror=write-strings"
        VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/djfdyuruiry/index.json,readwrite"
      run: |
        export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

        jq '(.configurePresets[] | select(.name == "release")).cacheVariables["CMAKE_PREFIX_PATH"] = "${sourceDir}/build/${{ steps.set_preset.outputs.preset }}/vcpkg_installed/uni-osx"' CMakePresets.json > /tmp/CMakePresets1.json
        jq '(.configurePresets[] | select(.name == "release")).cacheVariables["VCPKG_TARGET_TRIPLET"] = "uni-osx"' /tmp/CMakePresets1.json > /tmp/CMakePresets2.json
        jq '(.configurePresets[] | select(.name == "release")).cacheVariables["VCPKG_MANIFEST_INSTALL"] = "OFF"' /tmp/CMakePresets2.json > CMakePresets.json

        cp cmake/uni-osx.cmake .vcpkg/triplets
  
        # build using universal triplet
        cmake --workflow --preset ${{ steps.set_preset.outputs.preset }}

    # BUG: separate out ra and td into sep archives (data files cluttering zip)
    - name: Create archives
      run: |
        mkdir artifact
        
        if [ "${{ steps.set_preset.outputs.preset }}" != "nco-tiberian-dawn" ]; then
          dsymutil build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillara.app/Contents/MacOS/vanillara -o build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillara.dSYM
          strip -Sx build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillara.app/Contents/MacOS/vanillara
          dylibbundler --create-dir --bundle-deps --overwrite-files --dest-dir ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillara.app/Contents/libs --fix-file build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillara.app/Contents/MacOS/vanillara
          7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillara.app
          7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}-debug.zip ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillara.dSYM
        fi

        if [ "${{ steps.set_preset.outputs.preset }}" != "nco-red-alert" ]; then
          dsymutil build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillatd.app/Contents/MacOS/vanillatd -o build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillatd.dSYM
          strip -Sx build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillatd.app/Contents/MacOS/vanillatd
          dylibbundler --create-dir --bundle-deps --overwrite-files --dest-dir ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillatd.app/Contents/libs --fix-file build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillatd.app/Contents/MacOS/vanillatd
          7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillatd.app
          7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}-debug.zip ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillatd.dSYM

          # data packs (remove *.bat scripts first)
          rm -f resources/data/td/*.bat
          7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}.zip ./resources/data/td/*

          # lua library
          mkdir -p lua/nco
        
          cp -rv build/${{ steps.set_preset.outputs.preset }}/vcpkg_installed/*/tools/lua/* lua/nco

          cp -rv common/lua/scripts/nco/* lua/nco
          cp -rfv tiberiandawn/lua/scripts/nco/* lua/nco

          7z a vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}.zip ./lua
        fi

    - name: Add internal tools to archive
      run: |
        dsymutil build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillamix -o build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillamix.dSYM
        strip -Sx build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillamix
        7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillamix
        7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}-debug.zip ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillamix.dSYM

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2
        path: artifact

    - name: Upload development release
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
      uses: softprops/action-gh-release@v2
      with:
        name: Development Build
        tag_name: "latest"
        prerelease: true
        files: |
          artifact/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload tagged release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifact/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
