name: macos

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      preset:
        description: 'Build preset (e.g., nco-tiberian-dawn)'
        required: false
        default: 'nco-tiberian-dawn'

  pull_request:
    paths:
      - .clang-format
      - CMake**
      - vcpkg**
      - .github/workflows/macos.yml
      - cmake/**
      - common/**
      - redalert/**
      - resources
      - tests/**
      - tiberiandawn/**
      - tools/**

  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}__macos
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  NUGET_URL: https://nuget.pkg.github.com/djfdyuruiry/index.json

jobs:
  vanilla-macos:
    runs-on: macos-15
    strategy:
      matrix:
        preset:
          - "${{ github.event.inputs.preset || 'nco-tiberian-dawn' }}"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 0
        ref: "${{ github.event.pull_request.head.sha || github.sha }}"

    - name: Set Git Info
      id: gitinfo
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Install homebrew deps
      run: |
        brew install dylibbundler imagemagick jinja2-cli mono

    - name: Scan for Preset Files in Changes
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          ci:
            - .github/workflows/linux.yml
          nco:
            - .clang-format
            - CMake**
            - cmake/**
            - common/**
            - resources
            - tools/**
          ra:
            - redalert/**
          td:
            - tiberiandawn/**

    - name: Set Preset
      id: set_preset
      run: |
        PRESET=""

        if [ "${{ steps.changes.outputs.nco }}" = "true" ]; then
          echo "Changes to shared files detected - building everything using cmake preset: nco"
          PRESET="nco"
        elif [ "${{ steps.changes.outputs.ra }}" = "true" ] && [ "${{ steps.changes.outputs.td }}" = "true" ]; then
          echo "Red Alert & Tiberian Dawn changes detected - building both using cmake preset: nco"
          PRESET="nco"
        elif [ "${{ steps.changes.outputs.ra }}" = "true" ] ; then
          echo "Only Red Alert changes detected - using cmake preset: nco-red-alert"
          PRESET="nco-red-alert"
        elif [ "${{ steps.changes.outputs.td }}" = "true" ]; then
          echo "Only Tiberian Dawn changes detected - using cmake preset: nco-tiberian-dawn"
          PRESET="nco-tiberian-dawn"
        elif [ "${{ steps.changes.outputs.ci }}" = "true" ]; then
          echo "Workflow yml changes detected - testing workflow changes using cmake preset: nco"
          PRESET="nco"
        else
          echo "WARNING: Unable to match changed files to a preset - defaulting to building everything using cmake preset: nco"
          PRESET="nco"
        fi

        echo "preset=${PRESET}" >> $GITHUB_OUTPUT

    - name: Init vcpkg
      run: |
        ./scripts/bin/vcpkg --init
        ./scripts/bin/vcpkg fetch nuget

    - name: Init vcpkg Binary Cache
      run: |
        cd "$(dirname "$(./scripts/bin/vcpkg fetch nuget)")"

        mono nuget.exe sources add \
          -Source "${{ env.NUGET_URL }}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "djfdyuruiry" \
          -Password "${{ secrets.GITHUB_TOKEN }}"

        mono nuget.exe setapikey "${{ secrets.GITHUB_TOKEN }}" \
          -Source "${{ env.NUGET_URL }}"

    - name: Create Universal vcpkg Triplet
      env:
        VCPKG_BINARY_SOURCES: "clear;nuget,${{ env.NUGET_URL }},readwrite"
      run: |
        installed_path=build/${{ steps.set_preset.outputs.preset }}/vcpkg_installed

        mkdir -p $installed_path

        mkdir /tmp/vcpkg-arm64
        mkdir /tmp/vcpkg-x64

        cp cmake/vcpkg/triplets/arm64-osx14.cmake .vcpkg/triplets
        cp cmake/vcpkg/triplets/x64-osx14.cmake .vcpkg/triplets

        ./scripts/bin/vcpkg install --triplet=arm64-osx14 --x-install-root=/tmp/vcpkg-arm64
        ./scripts/bin/vcpkg install --triplet=x64-osx14 --x-install-root=/tmp/vcpkg-x64

        python -m venv /tmp/vcpkg.venv
        . /tmp/vcpkg.venv/bin/activate

        python -m ensurepip
        python -m pip install lipomerge

        python -m lipomerge /tmp/vcpkg-arm64/arm64-osx14 /tmp/vcpkg-x64/x64-osx14 $installed_path/uni-osx14

    - name: Build Vanilla Conquer
      env:
        CMAKE_MAKE_PROGRAM: ninja
        CMAKE_OSX_ARCHITECTURES: "arm64;x86_64"
        VC_CXX_FLAGS: "-w;-Wwrite-strings;-Werror=write-strings"
        VCPKG_BINARY_SOURCES: "clear;nuget,${{ env.NUGET_URL }},readwrite"
      run: |
        export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

        jq '(.configurePresets[] | select(.name == "release")).cacheVariables["VCPKG_TARGET_TRIPLET"] = "uni-osx14"' CMakePresets.json > /tmp/CMakePresets.json
        jq '(.configurePresets[] | select(.name == "release")).cacheVariables["VCPKG_MANIFEST_INSTALL"] = "OFF"' /tmp/CMakePresets.json > /tmp/CMakePresets1.json
        jq '(.configurePresets[] | select(.name == "release")).cacheVariables["CMAKE_OSX_DEPLOYMENT_TARGET"] = "14.0"' /tmp/CMakePresets1.json > CMakePresets.json
  
        cp cmake/vcpkg/triplets/uni-osx14.cmake .vcpkg/triplets

        # build using universal triplet
        cmake --workflow --preset ${{ steps.set_preset.outputs.preset }}

    # BUG: separate out ra and td into sep archives (data files cluttering zip)
    - name: Create archives
      run: |
        mkdir artifact
        
        # ninja build log (useful for profiling compilation)
        7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}-debug.zip build/nco/.ninja_log

        if [ "${{ steps.set_preset.outputs.preset }}" != "nco-tiberian-dawn" ]; then
          # prep debug symbols
          dsymutil build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/ra/vanillara.app/Contents/MacOS/vanillara -o build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillara.dSYM
          strip -Sx build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/ra/vanillara.app/Contents/MacOS/vanillara
          dylibbundler --create-dir --bundle-deps --overwrite-files --dest-dir ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/ra/vanillara.app/Contents/libs --fix-file build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/ra/vanillara.app/Contents/MacOS/vanillara

          # ra bundle
          7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/ra

          # debug symbols
          7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}-debug.zip ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillara.dSYM
        fi

        if [ "${{ steps.set_preset.outputs.preset }}" != "nco-red-alert" ]; then
          # prep debug symbols
          dsymutil build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/td/vanillatd.app/Contents/MacOS/vanillatd -o build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillatd.dSYM
          strip -Sx build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/td/vanillatd.app/Contents/MacOS/vanillatd
          dylibbundler --create-dir --bundle-deps --overwrite-files --dest-dir ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/td/vanillatd.app/Contents/libs --fix-file build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/td/vanillatd.app/Contents/MacOS/vanillatd

          # td bundle
          rm -f build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/td/*.bat
          7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/td

          # debug symbols
          7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}-debug.zip ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillatd.dSYM
        fi

    - name: Add internal tools to archive
      run: |
        dsymutil build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillamix -o build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillamix.dSYM
        strip -Sx build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillamix
        7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillamix
        7z a artifact/vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2-${{ steps.gitinfo.outputs.sha_short }}-debug.zip ./build/${{ steps.set_preset.outputs.preset }}/RelWithDebInfo/vanillamix.dSYM

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vanilla-conquer-${{ steps.set_preset.outputs.preset }}-macos-clang-universal2
        path: artifact

    - name: Upload development release
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
      uses: softprops/action-gh-release@v2
      with:
        name: Development Build
        tag_name: "latest"
        prerelease: true
        files: |
          artifact/*

    - name: Upload tagged release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifact/*
