name: deploy-wiki

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - wiki/**

jobs:
  deploy-wiki:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions4gh/configure-wiki@v1
      - uses: actions4gh/deploy-wiki@v1
