name: windows

on:
  workflow_dispatch:
    inputs:
      preset:
        description: 'Build preset (e.g., nco-tiberian-dawn)'
        required: false
        default: 'nco-tiberian-dawn'
      arch_win:
        description: 'Windows architecture (e.g., Win64)'
        required: false
        default: 'Win64'
      arch_lin:
        description: 'Linux architecture (e.g., x86_64)'
        required: false
        default: 'x86_64'

  pull_request:
    paths: &change-paths
      - .clang-format
      - CMake**
      - .github/workflows/windows.yml
      - cmake/**
      - common/**
      - redalert/**
      - resources
      - tiberiandawn/**
      - tools/**

  push:
    branches:
      - main
    paths: *change-paths

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  # TODO: Remaster compatibility
  # remaster_msvc:
  #   runs-on: windows-2022
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       submodules: 'true'
  #       fetch-depth: 0
  #       ref: "${{ github.event.pull_request.head.sha || github.sha }}"

  #   - uses: ilammy/msvc-dev-cmd@v1.13.0
  #     with:
  #       arch: x86
        
  #   - name: Set Git Info
  #     id: gitinfo
  #     shell: pwsh
  #     run: |
  #       $gitoutput = git rev-parse --short HEAD
  #       echo "sha_short=${gitoutput}" >> $env:GITHUB_OUTPUT
        
  #   - name: Install Dependencies
  #     run: |
  #       Invoke-WebRequest -Uri https://github.com/ninja-build/ninja/releases/download/v1.10.1/ninja-win.zip -OutFile $Env:TEMP\ninja-win.zip
  #       Expand-Archive $Env:TEMP\ninja-win.zip -DestinationPath $Env:TEMP\ninja
  #       echo "$Env:TEMP\ninja" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
  #       ninja --version

  #   - name: Build Vanilla Conquer
  #     env:
  #       VC_CXX_FLAGS: "/Zc:strictStrings;-wd4244;-wd4018;-wd4291;-wd4101;-wd4267;-wd4200"
  #     run: |
  #       cmake --workflow --preset remaster

  #   - name: Create archives
  #     shell: bash
  #     run: |
  #       mkdir artifact
  #       7z a artifact/vanilla-conquer-remasterdll-msvc-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/remaster/RelWithDebInfo/RedAlert.dll ./build/remaster/RelWithDebInfo/TiberianDawn.dll
  #       7z a artifact/vanilla-conquer-remasterdll-msvc-${{ steps.gitinfo.outputs.sha_short }}-debug.zip ./build/remaster/RelWithDebInfo/RedAlert.pdb ./build/remaster/RelWithDebInfo/TiberianDawn.pdb
  #       7z a artifact/vanilla-ra-remaster-mod-msvc-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/remaster/Vanilla_RA
  #       7z a artifact/vanilla-td-remaster-mod-msvc-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/remaster/Vanilla_TD
        
  #   - name: Upload artifact
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: vanilla-conquer-remaster-msvc
  #       path: artifact

  #   - name: Upload development release
  #     if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
  #     uses: softprops/action-gh-release@v2
  #     with:
  #       name: Development Build
  #       tag_name: "latest"
  #       prerelease: true
  #       files: |
  #         artifact/*
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #   - name: Upload tagged release
  #     if: ${{ startsWith(github.ref, 'refs/tags/') }}
  #     uses: softprops/action-gh-release@v2
  #     with:
  #       files: |
  #         artifact/*
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  vanilla_win_msvc:
    runs-on: windows-2022
    strategy:
      matrix:
        preset:
          - "${{ github.event.inputs.preset || 'nco-tiberian-dawn' }}"
        arch:
          - win: "${{ github.event.inputs.arch_win || 'Win64' }}"
            lin: "${{ github.event.inputs.arch_lin || 'x86_64' }}"
            cmd: x64

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 0
        ref: "${{ github.event.pull_request.head.sha || github.sha }}"
        
    - uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: ${{ matrix.arch.cmd }}
        
    - name: Set Git Info
      id: gitinfo
      shell: pwsh
      run: |
        $gitoutput = git rev-parse --short HEAD
        echo "sha_short=${gitoutput}" >> $env:GITHUB_OUTPUT

    - name: Install Dependencies
      id: deps
      run: |
        Invoke-WebRequest -Uri https://www.libsdl.org/release/SDL2-devel-2.0.12-VC.zip -OutFile SDL2-devel.zip
        Invoke-WebRequest -Uri https://github.com/ninja-build/ninja/releases/download/v1.10.1/ninja-win.zip -OutFile $Env:TEMP\ninja-win.zip
        Invoke-WebRequest -SkipCertificateCheck -Uri https://www.openal-soft.org/openal-binaries/openal-soft-1.21.0-bin.zip -OutFile openal-soft-1.21.0-bin.zip
        Expand-Archive SDL2-devel.zip -DestinationPath .
        Expand-Archive $Env:TEMP\ninja-win.zip -DestinationPath $Env:TEMP\ninja
        Expand-Archive openal-soft-1.21.0-bin.zip -DestinationPath .
        echo "$Env:TEMP\ninja" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        ninja --version
        echo "magickpath=$(Split-Path -Path $(Get-Command magick).Path -Parent)" >> $env:GITHUB_OUTPUT
        Rename-Item openal-soft-1.21.0-bin\bin\${{ matrix.arch.win }}\soft_oal.dll OpenAL32.dll

    - name: Build Vanilla Conquer
      env:
        CMAKE_FIND_ROOT_PATH: "SDL2-2.0.12;openal-soft-1.21.0-bin;${{ steps.deps.outputs.magickpath }}"
        VC_CXX_FLAGS: "/Zc:strictStrings;-wd4244;-wd4018;-wd4291;-wd4101;-wd4267;-wd4200"
      run: |
        New-Item -Path "build/${{ matrix.preset }}/RelWithDebInfo" -ItemType Directory
        Copy-Item -Path "SDL2-2.0.12\lib\${{ matrix.arch.cmd }}\SDL2.dll" -Destination build/${{ matrix.preset }}/RelWithDebInfo
        cmake --workflow --preset ${{ matrix.preset }}
        
    - name: Create archives
      if: ${{ matrix.preset != 'testing' &&  matrix.preset != 'nonet' }}
      shell: bash
      run: |
        mkdir artifact
        # 7z a artifact/vanilla-conquer-${{ matrix.preset }}-win-msvc-${{ matrix.arch.lin }}-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/${{ matrix.preset }}/RelWithDebInfo/vanillatd.exe ./SDL2-2.0.12/lib/${{ matrix.arch.cmd }}/SDL2.dll ./openal-soft-1.21.0-bin/bin/${{ matrix.arch.win }}/OpenAL32.dll
        # ./build/${{ matrix.preset }}/RelWithDebInfo/vanillara.exe
        7z a artifact/vanilla-conquer-${{ matrix.preset }}-win-msvc-${{ matrix.arch.lin }}-${{ steps.gitinfo.outputs.sha_short }}-debug.zip ./build/${{ matrix.preset }}/RelWithDebInfo/vanillatd.pdb
        # ./build/${{ matrix.preset }}/RelWithDebInfo/vanillara.pdb

    - name: Add internal tools to archive
      if: ${{ matrix.preset == 'internal' || matrix.preset == 'nco-tiberian-dawn' }}
      run: |
        7z a artifact/vanilla-conquer-${{ matrix.preset }}-win-msvc-${{ matrix.arch.lin }}-${{ steps.gitinfo.outputs.sha_short }}.zip ./build/${{ matrix.preset }}/RelWithDebInfo/vanillamix.exe
        7z a artifact/vanilla-conquer-${{ matrix.preset }}-win-msvc-${{ matrix.arch.lin }}-${{ steps.gitinfo.outputs.sha_short }}-debug.zip ./build/${{ matrix.preset }}/RelWithDebInfo/vanillamix.pdb
    
    - name: Upload artifact
      if: ${{ matrix.preset != 'testing' &&  matrix.preset != 'nonet' }}
      uses: actions/upload-artifact@v4
      with:
        name: vanilla-conquer-${{ matrix.preset }}-win-msvc-${{ matrix.arch.lin }}
        path: artifact
        
    - name: Upload development release
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && matrix.preset != 'testing' &&  matrix.preset != 'nonet' }}
      uses: softprops/action-gh-release@v2
      with:
        name: Development Build
        tag_name: "latest"
        prerelease: true
        files: |
          artifact/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload tagged release
      if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.preset != 'testing' &&  matrix.preset != 'nonet' }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          artifact/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
